app:
  spider_path: "/movies-spider"
  spider_path_name: "MoviesSpider"
  debug_path: "/debug"
  debug_path_name: "Debug"
  spider_mod: "async"
  debug_mod: "true"
server:
  run_mode: 'debug'
  http_port: 8080
  read_timeout: 60
  write_timeout: 60
  server_timeout: 10

redis:
  host: '127.0.0.1'
  port: 6379
  scheme: 'tcp'
  alias: 'RedisLock'
  user:
  password:
  ttl: 3000


mysql:
  host: '127.0.0.1'
  port: 3306
  scheme: 'dvapay'
  user:  "root"
  password: "root"

cron:
  time_spider: "0 0 1 * * ?"

base_url:
  douban: "https://movie.douban.com/top250"
  tiankong: "https://api.tiankongapi.com/api.php/provide/vod"
  tencent: ""

logger:
  default_name: 'go-spider'
  path: './logs'